baseurl = "/"
languageCode = "en-us"
title = "Stephen Zhang"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
# [[menu.main]]
#     name = "About me"
#     url = "/about/"
#     weight = 1

# [[menu.feed]]
#     name = "Subscribe"
#     url = "/index.xml"

[params]
    description = "Stephen Zhang"
    footer = "[Twitter](https://twitter.com/_zsteve) | Theme: [Hugo Classic](https://github.com/goodroot/hugo-classic)"
    custom_css = ["css/theme-override.css"]
